spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: practice-consumer
          uri: lb://practice-consumer
          predicates:
            - Path=/practice/**
          filters:
            - StripPrefix=1



server:
  port: 8088

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka
